export const UserActionTypes = {


    FETCH_USERS_REQUEST: "FETCH_USERS_REQUEST",
    FETCH_USERS_FAILED: "FETCH_USERS_FAILED",
    FETCH_USERS_SUCESS: "FETCH_USERS_SUCESS",
    VALID_USER_SUCESS: "VALID_USER_SUCESS",
    VALID_USER_FAILED: "VALID_USER_FAILED"

}